import Footer from "@/components/Footer";
import Provider from "@/components/Provider";
import "@/styles/globals.css";

export const metadata = {
  title: "Vitaplant - CRM System",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative">
        <Provider>
          <main className="min-h-screen pb-24">{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
