import Footer from "@/components/Footer";
import Provider from "@/components/Provider";
import "@/styles/globals.css";
import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: "Vitaplant - CRM System",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="relative">
        <Provider>
          <Link href="/" className="absolute -z-10">
            <Image alt="Vitaplant Logo" src="/assets/vitaplant_logo.png" />
          </Link>
          <main className="min-h-screen p-8 pb-24">{children}</main>
          <div className="absolute w-full h-full top-0 left-0 background-image-container pointer-events-none"></div>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
